# Generated by Django 4.2 on 2023-05-17 19:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('Women', 'Women'), ('Children', 'Children'), ('Men', 'Men')], max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'M'), ('L', 'L'), ('S', 'S'), ('XL', 'XL')], max_length=50, verbose_name='Размер'),
        ),
    ]
