# Generated by Django 4.2 on 2023-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='about',
            field=models.TextField(max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Цена'),
        ),
    ]
